---
dns_nameservers: ['192.168.1.199', '192.168.1.147']
dns_remove_resolvconf: true
dns_domain: "apopx.net"
dns_searchs:
  - "{{dns_domain}}"
dns_options: []
dns_dhclient_rule: "supersede" # can be supersede or prepend

dns_dhclient_file: "/etc/dhcp/dhclient.conf"
dns_forced_in_dhclientconf: "{{ansible_os_family == 'Debian' or ansible_os_family == 'Redhat'}}"
