---

- name: restart ldap-debian
  service: name={{ item.name }} state={{ item.state  }} 
  with_items:
   - { name: 'sssd', state: 'restarted', update_cache: 'yes' }
   - { name: 'nslcd', state: 'restarted', update_cache: 'yes' }
   - { name: 'nscd', state: 'restarted', update_cache: 'yes' }
  when: ansible_os_family == "Debian"

- name: restart ldap-centos
  service: name={{ item.name }} state={{ item.state }}
  with_items:
   - { name: 'nslcd', state: 'restarted', update_cache: 'yes' }
   - { name: 'nscd', state: 'restarted', update_cache: 'yes' } 
  when: ansible_os_family == "RedHat"
