---

- name: Install ldap software for Debian
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
   - sssd
   - ruby-ldap
   - libpam-ldapd
  when: ansible_os_family == "Debian"

- name: Install ldap software for RedHat
  yum: pkg={{ item }} state=installed update_cache=yes
  with_items:
   - openldap-clients
   - nss-pam-ldapd
  when: ansible_os_family == "RedHat"

- include: configure.yml
- include: start.yml

