---

- name: "Installing MySQL for RedHat"
  yum: pkg={{ item }} state=installed
  with_items:
   - mariadb-server
   - mariadb
  when: ansible_os_family == "RedHat"

- name: "Start Mariadb"
  service: name=mariadb state=started enabled=yes

- name: "Installing MySQL for Debian"
  apt: pkg={{ item }} state=installed
  with_items:
   - mysql-server
  when: ansible_os_family == "Debian"

- include: repos.yml
  when: ansible_os_family == "RedHat"


-  include: configure.yml

