---

- name: Adding ssh files
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
   - { src: 'sudoers', dest: '/etc/sudoers', owner: 'root', group: 'root', mode: '0644' }
   - { src: 'sshd_config', dest: '/etc/ssh/sshd_config', owner: 'root', group: 'root', mode: '0644' }
   - { src: 'ldapssh', dest: '/home/adrian/ldapssh', owner: 'root', group: 'root', mode: '755' }	
  notify: restart ssh
