- name: Enable firewalld
  service: name=firewalld state=started enabled=yes

- name: Allow http/https
  command: firewall-cmd --zone=dmz --permanent --add-service=http --add-service=https

- name: Bounce firewalld
  service: name=firewalld state=restarted
