- name: Adding sshd config
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
   - { src: 'sshd.conf', dest: '/etc/ssh/sshd.conf', owner: 'root', group: 'root', mode: '0644' }
  notify: restart ssh
