---

- name: Adding ntp file
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
   - { src: 'ntp.conf-debian', dest: '/etc/ntp.conf', owner: 'root', group: 'root', mode: '0644' }
   - { src: 'fstab', dest: '/etc/fstab', owner: 'root', group: 'root', mode: '0644' }
  when: ansible_os_family == "Debian"
  notify: restart ntp debian  
  
- name: Adding ntp file
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
   - { src: 'ntp.conf-centos', dest: '/etc/ntp.conf', owner: 'root', group: 'root', mode: '0644' }
   - { src: 'fstab', dest: '/etc/fstab', owner: 'root', group: 'root', mode: '0644' }
  when: ansible_os_family == "RedHat"
  notify: restart ntpd centos

- file: 
    src: /usr/share/zoneinfo/GB
    dest: /etc/localtime
    state: link

- name: Enable firewalld
  service: name=firewalld state=started enabled=yes
  when: ansible_os_family == "RedHat"

- name: Allow ntp
  command: firewall-cmd --add-service=ntp --permanent
  when: ansible_os_family == "RedHat"

- name: Bounce firewalld
  service: name=firewalld state=restarted
  when: ansible_os_family == "RedHat"

- name: take immutable file
  command: chattr -i /etc/resolv.conf

- name: Adding resolf.conf
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
   - { src: 'resolv.conf', dest: '/etc/resolv.conf', owner: 'root', group: 'root', mode: '0644' }

- name: immutable file
  command: chattr +i /etc/resolv.conf
