---

- name: "Installing Packages for centos"
  yum: pkg={{ item }} state=installed
  with_items:
   - nano
   - ntp
   - iotop
   - libsemanage-python	 
   - nfs-utils
  when: ansible_os_family == "RedHat"

- name: "Installing Packages for debian"
  apt: pkg={{ item }} state=present
  with_items:
   - nano
   - ntp
   - iftop
   - iotop
   - nfs-common
  when: ansible_os_family == "Debian"

- include: configure.yml
- include: startntp.yml
