---

- name: start ntp 
  service: name={{ item.name }} state={{ item.state  }} 
  with_items:
   - { name: 'ntp', state: 'started' }
  when: ansible_os_family == "Debian"

- name: start ntpd
  service: name={{ item.name }} state={{ item.state  }}
  with_items:
   - { name: 'ntpd', state: 'started' }
  when: ansible_os_family == "RedHat"

