  - name: Yum install Zabbix release in RHEL or CentOS
    yum: name=http://repo.zabbix.com/zabbix/3.2/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-3.2-1.el{{ ansible_distribution_major_version }}.noarch.rpm
    when: ansible_os_family == "RedHat"
    
  - name: Yum install Zabbix agent
    yum: name=zabbix-agent
    when: ansible_os_family == "RedHat"
