---

  - lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="{{ item.var }}=" line="{{ item.var }}={{ item.value }}"
    with_items:
      - { var: "ServerActive", value: "{{zabbix_agent_server}}:{{zabbix_agent_server_port}}"}
      - { var: "Hostname", value: "{{ansible_hostname}}"}
      - { var: "Server", value: "{{zabbix_agent_server}}"}
      - { var: "HostMetadataItem", value: "system.uname"}
      - { var: "RefreshActiveChecks", value: "60"}
    notify: restart zabbix-agent
     
  - lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="{{ item }}=" state=absent
    with_items:
      - "Include="
    notify: restart zabbix-agent

  - name: Enable firewalld
    service: name=firewalld state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - name: Allow Zabbix
    command: firewall-cmd --permanent --add-port=10050/tcp
    when: ansible_os_family == "RedHat"

  - name: Bounce firewalld
    service: name=firewalld state=restarted
    when: ansible_os_family == "RedHat"
    notify: restart zabbix-agent
