---
  - name: Download Zabbix Debian 9 (Stretch) release deb file
    get_url: 
      url="http://repo.zabbix.com/zabbix/3.2/debian/pool/main/z/zabbix-release/zabbix-release_3.2-1+stretch_all.deb"
      dest="/tmp/zabbix-release_3.2-1.deb"
    when: ansible_os_family == "Debian" and ansible_distribution == "Debian" and ansible_distribution_major_version|int == 9

  - name: Apt install Zabbix release in Ubuntu/Debian
    apt: deb="/tmp/zabbix-release_3.2-1.deb"
    when: ansible_os_family == "Debian"

  - name: Yum install Zabbix release in RHEL or CentOS
    yum: name=http://repo.zabbix.com/zabbix/3.2/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-3.2-1.el{{ ansible_distribution_major_version }}.noarch.rpm
    when: ansible_os_family == "RedHat"
    
  - name: Apt install Zabbix agent
    apt:
      name: zabbix-agent
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Yum install Zabbix agent
    yum: name=zabbix-agent
    when: ansible_os_family == "RedHat"
