- name: restart ssh
  service: name={{ item.name }} state={{ item.state  }} 
  with_items:
   - { name: 'ssh', state: 'restarted', update_cache: 'yes' }
  when: ansible_os_family == "Debian"

- name: restart ssh
  service: name={{ item.name }} state={{ item.state  }}
  with_items:
   - { name: 'sshd', state: 'restarted', update_cache: 'yes' }
  when: ansible_os_family == "RedHat"

