- name: "MySQL enabled for Centos?"
  service: name=mariadb state=started enabled=yes
  when: ansible_os_family == "RedHat"

- name "MySQL enabled for Debian?"
  service: name=mysql state started enabled yes
  when: ansible_os_family == "Debian"
