---

 - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
   seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
   when: ansible_os_family == "RedHat"

 - name: Enable firewalld
   service: name=firewalld state=started enabled=yes
   when: ansible_os_family == "RedHat"

 - name: Allow http/https
   command: firewall-cmd --add-service=http --permanent && firewall-cmd --add-service=https --permanent
   when: ansible_os_family == "RedHat"

 - name: Bounce firewalld
   service: name=firewalld state=restarted
   when: ansible_os_family == "RedHat"
