- name: "Installing Webserver Software"
  yum: name={{ item }}
  with_items:
   - httpd

- name: "http enabled?"
  service: name=httpd state=started enabled=yes

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
