- name: "Installing Webserver Software for Centos"
  yum: name={{ item }} state=present update_cache=yes
  with_items:
   - httpd
  when: ansible_os_family == "RedHat"

- name: "Installing Webserver Software for Debian"
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - apache2
  when: ansible_os_family == "Debian"

