---

  - name: Yum install Zabbix release in RHEL or CentOS
    yum: name=http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
    when: ansible_os_family == "RedHat"

  - name: Yum install php
    yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    when: ansible_os_family == "RedHat"



